server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: account-service
              uri: lb://ACCOUNT-SERVICE
              predicates:
                - Path=/accounts/**
            - id: card-service
              uri: lb://CARD-SERVICE
              predicates:
                - Path=/cards/**
            - id: loans-service
              uri: lb://LOANS-SERVICE
              predicates:
                - Path=/loans/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-ms: 10
    register-with-eureka: true
    fetch-registry: true
